# Generated by Django 2.2 on 2020-08-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghostname',
            old_name='comment_text',
            new_name='description',
        ),
    ]
